language: objective-c
rvm:
  - 2.0.0
gemfile:
  - Gemfile
cache: bundler
branches:
  only:
    - master
before_script:
  - export LANG=en_US.UTF-8
  - sudo easy_install pyyaml
  - sudo easy_install cpp-coveralls
script:
  - rake test:run
after_success:
  - rake test:coverage publish=yes