language: objective-c
rvm:
  - 1.9.3
gemfile:
  - Gemfile
cache: bundler
branches:
  only:
    - 2.0-develop
before_script:
  - sudo easy_install pyyaml
  - sudo easy_install cpp-coveralls
script:
  - rake test:run
after_success:
  - rake test:coverage
  - coveralls --no-gcov --verbose --exclude Pods --exclude Scripts --exclude PodioKit/V1 --exclude PodioKitTests/V1 